version: "3.9"
services:
  console:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: "csharp-beverage-prices-kata"
    volumes:
      - .:/app
    tty: true